#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=24:00:00
#SBATCH --mem=10GB
#SBATCH --job-name=save_test
#SBATCH --gres=gpu:1
#SBATCH --mail-type=END
#SBATCH --mail-user=xl2053@nyu.edu
#SBATCH --output=/scratch/xl2053/nlp/hw2_data/logs/batch-%j.log

RUNDIR=$HOME/NLP_with_Representation_Learning/rnn_cnn_natural_lang_inference/
cd $RUNDIR

export PATH="/home/xl2053/miniconda3/bin:$PATH"
. /home/xl2053/miniconda3/etc/profile.d/conda.sh
conda activate
conda activate nlpclass

python demo.py

